---
- name: ansible dev vm
  hosts: all
  become: true
  become_user: root
  roles:
    - role: ultral.ansible_development
  post_taks:
     - name: Install git
       package:
         name: git
         state: present
       retries: 5
       delay: 2
